### ISSUE TITLE
Changing from Sandbox to Production

### ISSUE THREAD

**Issue by walosha** [pryme0/sudo-africa-cards-module#1]
Thumbs up and weldone.
@pryme0 
how do i change the base url from sanbox to production|
`export const Sudo_AFRICA_BASE_URL = ' https://api.sandbox.sudo.cards` to https://app.sudo.africa which looks like a constant

**Comment by pryme0** [comment]
@walosha My apologies for the oversight 

I published an updated version that  fixes this problem
